POST http://localhost:8888/register
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "1234"
}

###

POST http://localhost:8888/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "1234"
}